# Generated by Django 4.1.2 on 2023-01-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
        ('AdminApp', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInformation',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='UserInformation',
        ),
    ]
