# Generated by Django 4.1.2 on 2023-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_userinfo_userinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'UserInfor',
            },
        ),
    ]
