# Generated by Django 4.1.2 on 2023-01-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_userinfor'),
        ('UserApp', '0002_alter_mycart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
