# Generated by Django 4.1.2 on 2023-01-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_mycart_user'),
        ('AdminApp', '0007_delete_userinfor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInformation',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='UserInformation',
        ),
    ]
